version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: meetingapp
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  web:
    build: .
    command: /app/entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - DATABASE_HOST=db
      - DATABASE_NAME=meetingapp
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
    depends_on:
      - db

volumes:
  db_data:
